### ISSUE TITLE
file name formatting

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#18]
#### Issue is shown in the screenshot (5th pdf in the list). Notice the diff between the rest of the items.

![image](https://user-images.githubusercontent.com/12476526/46753842-c39ebc00-cc75-11e8-8ace-d98546b6d71c.png)

#### How to do this: https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

Some information on this issue can be found here #14

**Comment by JayaKrishnaNamburu** [comment]
Hi @alexweininger  i would like to contribute for this

**Comment by alexweininger** [comment]
@JayaKrishnaNamburu just pushed a fix to the dev branch I am going to make a pr soon.

Another issue should be make to try to truncate the url specifically at the end of a directory. So no directory names are cut off.

**Comment by alexweininger** [comment]
Closed with #19
