### ISSUE TITLE
File url truncating cuts of directory names

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#20]
File url truncating cuts of directory names

Since the file url is being truncated at the beginning of the string, sometimes the directory name is cut off. Somehow it should truncate at the optimal place so that it doesn't go over the width and does not cut off a directory name.

![image](https://user-images.githubusercontent.com/12476526/46756476-6c501a00-cc7c-11e8-9d9d-e6cf29911d9e.png)

#18 contains more info on this

**Comment by harshalitalele** [comment]
For CS305_hw3, it should be '...Classes\CS 305 Data Structures\homework\hw3.pdf'.
This is how you want it right?

**Comment by alexweininger** [comment]
@harshalitalele correct
