### ISSUE TITLE
Improve file icon appearance

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#21]
### Improve file icon appearance
- As of now the icons are not properly aligned vertically with the file name. 
- They also could be a bit larger to fit in with the file name font size.

![image](https://user-images.githubusercontent.com/12476526/46765784-cbba2400-cc94-11e8-864e-a29a98e26e51.png)

**Comment by jmannfeld** [comment]
I can work on this

**Comment by alexweininger** [comment]
@jmannfeld go for it! 

Feel free to discuss what you're planning to do with me!

**Comment by jmannfeld** [comment]
Is there a good way to inspect a plugin in chrome?

**Comment by alexweininger** [comment]
@jmannfeld The way I have always done it is just right click on the popup and inspect it from there. It is annoying since when you click away, the popup and the dev tools close.

Are you asking about that or about how to add RecentPDF to chrome so you can test it while developing?

**Comment by jmannfeld** [comment]
Yep, I was asking about inspecting the styles. I will try that

**Comment by jmannfeld** [comment]
How's this?
![recent-pdf](https://user-images.githubusercontent.com/16351524/46778335-44df6880-cce1-11e8-989e-9a12e7632a74.png)

**Comment by alexweininger** [comment]
Looks amazing! @jmannfeld 👍 😃 🎉 

If you're ready, you can PR and I'll take a look at it locally.

Thanks!

**Comment by alexweininger** [comment]
#24

**Comment by jmannfeld** [comment]
Thanks! 😀 Never worked on an extension before. Nice app!

**Comment by alexweininger** [comment]
Love the support! I encourage you to keep contributing!
