### ISSUE TITLE
what new settings do we want to add

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#25]
As the UI gets better and better, I think implementing some settings would be helpful.

For examples may be:
- dark mode
- choices for displaying the files
- how many files to display in a list

Any suggestions?

**Comment by dshubhadeep** [comment]
You should add the option to choose the no. of files to be displayed. 
IMO it doesn't need a dark mode for now.

**Comment by alexweininger** [comment]
I agree!

**Comment by dshubhadeep** [comment]
Do you want me to work on it or is it something you would like to do yourself ? 😛

**Comment by alexweininger** [comment]
You can go for it !

**Comment by dshubhadeep** [comment]
Cool, we can also add a bit of margin for the list items, it seems a bit congested.

**Comment by alexweininger** [comment]
I think this is a bigger issue and needs to be discussed more. But ya I agree it looks congested.
