### ISSUE TITLE
scrollbar

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#26]
As of now the scrollbar is hidden, I would like there to be a fancy small scrollbar that doesn't take up much space.  Maybe it can hide itself when not scrolling etc.

**Comment by JayaKrishnaNamburu** [comment]
Hi @alexweininger  i would to help for this.

**Comment by alexweininger** [comment]
@JayaKrishnaNamburu go for it! What are you thinking of doing?

**Comment by JayaKrishnaNamburu** [comment]
I need a little help in setting up the dev env as this will be my first time working with chrome extensions and I am excited about that and after that, I would like to custom style the scroll bar and achieve the needed.

**Comment by sinha-p** [comment]
@JayaKrishnaNamburu can i take it up ?

**Comment by alexweininger** [comment]
@JayaKrishnaNamburu Which parts do you need help for?

The process should go something like this:
1. Fork this repo
2. Clone that fork onto your machine
3. Go to chrome and go to the extensions menu
4. enable developer mode
5. load unpacked extension
6. select the root folder of the repo
7. when you change your local files of recent pdf the changes will be reflected in the recent pdf popup in chrome

**Comment by JayaKrishnaNamburu** [comment]
Thanks for the info, I will start with the process and update back 👍

**Comment by alexweininger** [comment]
#28

**Comment by alexweininger** [comment]
@JayaKrishnaNamburu feel free to update or change what @bradleyasu did
