### ISSUE TITLE
Unnecessary icons for local files?

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#34]
### Should the icons in the local file list be removed?

They will always be the same, dependant on your pdf viewer.
![image](https://user-images.githubusercontent.com/12476526/46910406-269f8580-cef8-11e8-88d0-1bd0250260d4.png)

**Comment by hitechcrafters** [comment]
Imo it's good to have icon there. The only thing which I'd change is size of it.

**Comment by alexweininger** [comment]
@hitechcrafters Want to create an issue and adjust the size to a bit smaller?
