### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#39]
Instead of a settings page, would it be possible to have settings within the popup?

Or should we continue with the settings being a whole page?

Let me know what you think.

**Comment by Crokky** [comment]
hello, could I try to work on it?

**Comment by Crokky** [comment]
Hello, Alex, I have a time to start working, what do I need to start from?

**Comment by alexweininger** [comment]
Probably start with getting familiar with how the tabs work right now. The logic is at the bottom of script.js

**Comment by Crokky** [comment]
Hi, Alex, I have a version of popup, how can I show u?

**Comment by alexweininger** [comment]
Awesome! Open up a pr!

**Comment by Crokky** [comment]
Sorry it is my first projct:) can me tell me how to open up or load :))
thanks

Dňa ut 23. 10. 2018 o 22:03 Alex Weininger <notifications@github.com>
napísala(a):

**Comment by alexweininger** [comment]
@Crokky sorry I've been super busy, I'll try to take a look at it this weekend and help you

**Comment by Crokky** [comment]
Hello, Alex, I have made pull request, could you check it? And I would like did you make code coverage of this project?

**Comment by alexweininger** [comment]
added in v2
