### ISSUE TITLE
Sorting feature

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#40]
I want to be able to sort my pdf list by different things. By name, by directory, by recently opened, by time accessed, etc.

How can we go about implementing the logic and the ui to enable this?  What do you think is the best way to do this?

**Comment by RisingGeek** [comment]
We can make a dropdown to select the mode of sorting. I would love to work on this.

**Comment by alexweininger** [comment]
Go for it!

**Comment by RisingGeek** [comment]
Is there any slack or gitter channel where we can talk?

**Comment by trblackw** [comment]
@RisingGeek @alexweininger feel free to contact me via discord `syntaxNinja #0515`

**Comment by alexweininger** [comment]
@trblackw my discord is mac#4164

**Comment by RisingGeek** [comment]
My discord is `rising_geek#5328`

**Comment by alexweininger** [comment]
@RisingGeek @trblackw I sent friend requests and I made a server for RecentPDF
