### ISSUE TITLE
readme needs to be updated

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#52]
since we moved to TS we have some readme sections to update.

**Comment by zohan4sh** [comment]
Hello, I can help with this, please describe what changes are needed with README.
Can you add this in hacktoberfest?!
Regards

**Comment by alexweininger** [comment]
Oops, looks like I kinda updated it already and forgot to close this issue. If you see any other things that need to be added to the readme then make a PR and i will add the Hacktoberfest tag to it.
