### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#59]

**Comment by RisingGeek** [comment]
I would like to work on this functionality.

**Comment by trblackw** [comment]
Hey @alexweininger 👋🏻
I'd like to work on this but I'm running into this issue (step 4 of Getting Started)
<img width="627" alt="image" src="https://user-images.githubusercontent.com/36317675/66258700-4ae21b00-e776-11e9-8ab9-502a6352b7c3.png">
It appears to be looking for a manifest file that doesn't exist. This is the first chrome extension I've worked on so forgive me if I'm overlooking something.

**Comment by alexweininger** [comment]
Make sure to select the `dist/` directory. This directory holds the output of the `src/` and the things Chrome needs to bundle the extension. (this is where the manifest.json file is located as well).

Hope this helps!

**Comment by trblackw** [comment]
@alexweininger Ah, you have to make sure to run `yarn/npm watch` first. Might want to add that to the readme even if it's implied. You mind assigning me this task?

**Comment by alexweininger** [comment]
Assigned the task to you, let me know if you have any other questions. Thanks!

**Comment by trblackw** [comment]
Hey man, can you point me in the right direction for enabling my chrome debugger to actually detect console statements or debuggers I place in the code for this extension. It seems like I can't get anything to trigger or log. So I'm stuck here!
<img width="557" alt="image" src="https://user-images.githubusercontent.com/36317675/66262388-7c75d900-e7ac-11e9-8ba1-6e5bdcf0f658.png">

**Comment by alexweininger** [comment]
Ya I remember this being a little tricky. Let me see what I can find out for you. What happens if you `Right click -> inspect element` within the chrome extension popup? I believe this is where the console output should be. (Rather than the debugger attached to the browser window itself)

**Comment by trblackw** [comment]
Ah I see! It's actually "inspect pop up" but thanks for the direction:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/36317675/66262489-3706db00-e7af-11e9-95fd-c49be9714088.png">

**Comment by alexweininger** [comment]
Awesome!

**Comment by trblackw** [comment]
@alexweininger Glad I can be the source of all your hacktoberfest treats 😉🎃

**Comment by trblackw** [comment]
@alexweininger maybe we can find a way to screen share or something in the next couple of days for you to walk me through this debugging process because it seems pretty hit or miss for me right now and it's hard for me to figure out what's going on. Especially being so used to a react environment 😛 I like the vanilla js aspect though.

**Comment by alexweininger** [comment]
Is it typescript that's giving you trouble?

**Comment by trblackw** [comment]
No I love typescript. It’s really the debugging process. I set breakpoints
and they aren’t hit. I set console logs and they don’t log. If I manually
inspect the chrome extension specifically I can see them sometimes after
the fact but not in real time and the window randomly goes away. It’s just
an environment I’m not familiar with I guess. I write React with typescript
on a daily basis but like I mentioned initially I’ve never messed with
chrome extensions so I guess I’m a bit out of my element.

**Comment by alexweininger** [comment]
I've dealt with similar issues before.

I found answers in [this post](https://stackoverflow.com/questions/5039875/debug-popup-html-of-a-chrome-extension) to be helpful.

One of the answers shows how to do this:

1. find the ID: for the recent pdf extension in chrome://chrome/extensions/

2. You can then load your popup in a regular window by
    `chrome-extension://id_of_your_application/index.html`

https://stackoverflow.com/questions/5039875/debug-popup-html-of-a-chrome-extension

**Comment by trblackw** [comment]
This is the ultimately the best solution (from the post you linked):

**Comment by alexweininger** [comment]
Closed in #109
