### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#66]
RecentPDF would love to have a new icon! The current icon is pretty average, and does't really tell anyone about RecentPDF. The current icons are located in `recent-pdf/dist/icons/`.

What do you think the icon should look like?

**Comment by zohan4sh** [comment]
I'll definetely work on this!
I think the color of the icon should be changed as almost all the pdf readers have a red color.
Also a good transparent icon with a appealing border and a cool pdf text or a symbol will look great.
what do you think?

**Comment by alexweininger** [comment]
@zohan4sh 

I agree! It might be best to come up with a few options and colors and we can decide on what we all like best.

I'm excited to see your work!

Thanks, I'll assign this task to you.

**Comment by zohan4sh** [comment]
Yeah ! I'll give my best to this task.

**Comment by zohan4sh** [comment]
Hey!
I have made some icons.
Please check them out. and also some readme errors have been solved.
I'll try to make some more and add them too! Choice is yours.
