### ISSUE TITLE
Truncating of file name

### ISSUE THREAD

**Issue by RisingGeek** [alexweininger/recent-pdf#68]
The filename of online PDFs are being truncated. This is a similar issue to #20 
Consider the example below. The filename should start with 1Final Scheme & syllabus...
![Screenshot from 2019-10-06 11-47-16](https://user-images.githubusercontent.com/37294158/66265167-4d547b80-e82f-11e9-8fb2-b27950f1d9d9.png)

**Comment by alexweininger** [comment]
When the filename is too long to fit on one line what would you like to see?

**Comment by RisingGeek** [comment]
I would like to see the first few words followed by ...
Shall I take up this issue?

**Comment by alexweininger** [comment]
Yes I can assign this issue to you @RisingGeek. Let me know if you have any questions!

**Comment by RisingGeek** [comment]
Sure!
