### ISSUE TITLE
Add a dark theme and let users switch between dark/light themes

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#69]
Add a dark theme for the popup that can be enabled/disabled in the extension settings.

**Comment by ShobhitRathi** [comment]
i can help with this

**Comment by alexweininger** [comment]
@ShobhitRathi awesome! There is currently no theme system in place, do you have an approach in mind?

**Comment by dheeraj-2000** [comment]
hey i can also help with this

**Comment by alexweininger** [comment]
@ShobhitRathi @dheeraj-2000 Cool, I think the most effective approach would be to create a theme system that loads in json values for colors of elements in the html. That way we can easily add/modify themes later.

**Comment by ShobhitRathi** [comment]
Does this satisfy your requirements?

**Comment by alexweininger** [comment]
#92 closes this issue

**Comment by alexweininger** [comment]
thanks @dborg291
