### ISSUE TITLE
Name of PDF instead of directory path

### ISSUE THREAD

**Issue by RisingGeek** [alexweininger/recent-pdf#73]
Name of PDF should be mentioned instead of the directory path for local files like it's being done for online PDFs. Currently, directory path is shown 2 times. Otherwise, It would not be possible to sort the PDFs by name. Refer #40

**Comment by alexweininger** [comment]
Can you show me a screenshot of RecentPDF showing the file path twice? 

My online file list looks like this: 
![image](https://user-images.githubusercontent.com/12476526/66279315-96bfbd80-e865-11e9-9f3f-c85988a9711d.png)

**Comment by RisingGeek** [comment]
It's in local file list not online.
![Screenshot from 2019-10-07 11-09-14](https://user-images.githubusercontent.com/37294158/66287343-029c3780-e8f3-11e9-83bd-dca5950fdd08.png)

**Comment by alexweininger** [comment]
Here is my local:
![image](https://user-images.githubusercontent.com/12476526/66287455-c1703d00-e88a-11e9-8781-6c4191e12cea.png)

**Comment by RisingGeek** [comment]
I think this issue is only for linux users. You are finding the last index of `\\` to find the name of the file naa?

**Comment by alexweininger** [comment]
Yep that's the issue!
[you can see the line of code here](https://github.com/alexweininger/recent-pdf/blob/374ee993fe0340b6141dbf9292e755739cb0f741/src/script.ts#L166)

**Comment by RisingGeek** [comment]
Check if the output is same if we use `/` istead of `\\`

**Comment by alexweininger** [comment]
See #74

**Comment by alexweininger** [comment]
Closed in #74
