### ISSUE TITLE
Add setting for number of files to show in list

### ISSUE THREAD

**Issue by alexweininger** [alexweininger/recent-pdf#81]
Right now default is 30. It would be nice if users could change this to any value.

**Comment by sandeshan** [comment]
Hey Alex, I can work on the code changes for this. Had a couple of questions:
- Do you think there should be a limit? (100, 1000 etc.).
- Should this be a text field that is validated or a Select/Dropdown with numbers?

**Comment by alexweininger** [comment]
@sandeshan great questions!

> Do you think there should be a limit? (100, 1000 etc.).

Hmm. Not that I think having over 1000 pdfs would cause issues, i just think that no one would get over 1000. So i think 1000 is a fine limit.

> Should this be a text field that is validated or a Select/Dropdown with numbers?

Mine as well make it a validated input. Since there isnt a reason why we want to restrict the number users enter. 

I also think that adding a reset settings to default button might be useful to add. I might create a new issue for that.

**Comment by sandeshan** [comment]
Created a PR with the change. Will try to address any feedback promptly. And I agree, a "Rest Settings" button would be useful but should be tackled separately.
